
CREATE TABLE DLP_MDL
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	MDL_NM		  VARCHAR2(100)  NULL ,
	DESCR		  VARCHAR2(2000)  NULL
);



CREATE UNIQUE INDEX DLP_MDL_PK ON DLP_MDL
(MDL_ID  ASC);



ALTER TABLE DLP_MDL
	ADD CONSTRAINT  DLP_MDL_PK PRIMARY KEY (MDL_ID);



CREATE TABLE DLP_PIPELN
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PIPELN_ID	  VARCHAR2(20)  NOT NULL ,
	PIPELN_NM	  VARCHAR2(100)  NULL ,
	DESCR		  VARCHAR2(2000)  NULL
);



CREATE UNIQUE INDEX DLP_PIPELN_PK ON DLP_PIPELN
(MDL_ID  ASC,PIPELN_ID  ASC);



ALTER TABLE DLP_PIPELN
	ADD CONSTRAINT  DLP_PIPELN_PK PRIMARY KEY (MDL_ID,PIPELN_ID);



CREATE TABLE DLP_PIPELN_DATA_PATH
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PIPELN_ID	  VARCHAR2(20)  NOT NULL ,
	DATA_ID		  VARCHAR2(20)  NOT NULL ,
	DATA_NM		  VARCHAR2(100)  NULL ,
	DATA_PATH	  VARCHAR2(200)  NULL ,
	DESCR		  VARCHAR2(2000)  NULL
);



CREATE UNIQUE INDEX DLP_PIPELN_DATA_PATH_PK ON DLP_PIPELN_DATA_PATH
(MDL_ID  ASC,PIPELN_ID  ASC,DATA_ID  ASC);



ALTER TABLE DLP_PIPELN_DATA_PATH
	ADD CONSTRAINT  DLP_PIPELN_DATA_PATH_PK PRIMARY KEY (MDL_ID,PIPELN_ID,DATA_ID);



CREATE TABLE DLP_PIPELN_PARAM
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PARAM_ID	  VARCHAR2(20)  NOT NULL ,
	PIPELN_ID	  VARCHAR2(20)  NOT NULL ,
	PARAM_NM	  VARCHAR2(100)  NULL ,
	PARAM_VAL	  VARCHAR2(100)  NULL ,
	PARAM_TYP	  VARCHAR2(20)  NULL ,
	PAR_PARAM_ID	  VARCHAR2(20)  NULL ,
	PAR_PARAM_VAL	  VARCHAR2(100)  NULL
);



CREATE UNIQUE INDEX DLP_PIPELN_PARAM_PK ON DLP_PIPELN_PARAM
(MDL_ID  ASC,PARAM_ID  ASC,PIPELN_ID  ASC);



ALTER TABLE DLP_PIPELN_PARAM
	ADD CONSTRAINT  DLP_PIPELN_PARAM_PK PRIMARY KEY (MDL_ID,PARAM_ID,PIPELN_ID);



CREATE TABLE DLP_PRJT
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PRJT_ID		  VARCHAR2(20)  NOT NULL ,
	PRJT_NM		  VARCHAR2(100)  NULL ,
	USER_ID		  VARCHAR2(20)  NULL ,
	DESCR		  VARCHAR2(2000)  NULL ,
	ST_CD		  VARCHAR2(20)  NULL ,
	RGST_DT_TM	  VARCHAR2(14)  NULL ,
	UPD_DT_TM	  VARCHAR2(14)  NULL
);



CREATE UNIQUE INDEX DLP_PRJT_PK ON DLP_PRJT
(MDL_ID  ASC,PRJT_ID  ASC);



ALTER TABLE DLP_PRJT
	ADD CONSTRAINT  DLP_PRJT_PK PRIMARY KEY (MDL_ID,PRJT_ID);



CREATE TABLE DLP_PRJT_PIPELN
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PRJT_ID		  VARCHAR2(20)  NOT NULL ,
	PIPELN_ID	  VARCHAR2(20)  NOT NULL ,
	CMPLT_YN	  CHAR(1)  NULL ,
	BAT_OP_YN	  CHAR(1)  NULL ,
	BAT_OP_ID	  VARCHAR2(20)  NULL ,
	OP_CD		  VARCHAR2(20)  NULL ,
	RGST_DT_TM	  VARCHAR2(14)  NULL ,
	START_DT_TM	  VARCHAR2(14)  NULL ,
	END_DT_TM	  VARCHAR2(14)  NULL
);



CREATE UNIQUE INDEX DLP_PRJT_PIPELN_PK ON DLP_PRJT_PIPELN
(MDL_ID  ASC,PRJT_ID  ASC,PIPELN_ID  ASC);



ALTER TABLE DLP_PRJT_PIPELN
	ADD CONSTRAINT  DLP_PRJT_PIPELN_PK PRIMARY KEY (MDL_ID,PRJT_ID,PIPELN_ID);



CREATE TABLE DLP_PRJT_PIPELN_PARAM
(
	MDL_ID		  VARCHAR2(20)  NOT NULL ,
	PRJT_ID		  VARCHAR2(20)  NOT NULL ,
	PIPELN_ID	  VARCHAR2(20)  NOT NULL ,
	PARAM_ID	  VARCHAR2(20)  NOT NULL ,
	PARAM_NM	  VARCHAR2(100)  NULL ,
	PARAM_VAL	  VARCHAR2(100)  NULL ,
	PARAM_TYP	  VARCHAR2(20)  NULL ,
	RGST_DT_TM	  VARCHAR2(14)  NULL ,
	UPD_DT_TM	  VARCHAR2(14)  NULL
);



CREATE UNIQUE INDEX DLP_PRJT_PIPELN_PARAM_PK ON DLP_PRJT_PIPELN_PARAM
(MDL_ID  ASC,PRJT_ID  ASC,PIPELN_ID  ASC,PARAM_ID  ASC);



ALTER TABLE DLP_PRJT_PIPELN_PARAM
	ADD CONSTRAINT  DLP_PRJT_PIPELN_PARAM_PK PRIMARY KEY (MDL_ID,PRJT_ID,PIPELN_ID,PARAM_ID);


